"""added amount

Revision ID: 470474583511
Revises: 09fef2e54af4
Create Date: 2024-02-19 13:33:15.356306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470474583511'
down_revision = '09fef2e54af4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
